### ISSUE TITLE
demo site not working

### ISSUE THREAD

**Issue by MROALI** [EasyAbp/Abp.PhoneNumberLogin#1]
Hello,
The demo site not working. can you please fix it ?

**Comment by gdlcf88** [comment]
Demo sites managed by @hueifeng but he is busy recently. For now, you can run the [PhoneNumberLoginSample](https://github.com/EasyAbp/Abp.PhoneNumberLogin/tree/main/samples/PhoneNumberLoginSample) to experience this module.
